module.exports = {
  //state
  NOT_LOADED: "NOT_LOADED",
  LOADING: "LOADING",
  LOADED: "LOADED",
  ADDED_TO_CART: "ADDED_TO_CART",

  //actions
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOADING_PRODUCTS: "LOADING_PRODUCTS",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART"

}
