module.exports = {
  //state
  NOT_LOADED: "NOT_LOADED",
  LOADING: "LOADING",
  LOADED: "LOADED",

  //actions
  LOAD_PRODUCTS: "LOAD_PRODUCTS",
  LOADING_PRODUCTS: "LOADING_PRODUCTS",
  ADD_PRODUCTS: "ADD_PRODUCTS"

}
