module.exports = {
  //actions category
  SETTINGS_CATEGORY_SELECTED: "SETTINGS_CATEGORY_SELECTED",
  LOADING: "LOADING",
  //actions while cahnging fields
  FIELD_CHANGING: "FIELD_CHANGING",
  //state category
  EMAIL_SOC_NETWORKS_SELECTED: "EMAIL_SOC_NETWORKS_SELECTED",
  INITIALS_SELECTED: "INITIALS_SELECTED",
  ADDRESSES_SELECTED: "ADDRESSES_SELECTED",
  LOADING_CATEGORY: "LOADING_CATEGORY",
  //state while changing fields
  NOTHING_CHANGES: "NOTHING_CHANGES",
  CHANGING_USERNAME_AVATAR: "CHANGING_USERNAME_AVATAR"
}
