module.exports = {
  //actions
  SETTINGS_CATEGORY_SELECTED: "SETTINGS_CATEGORY_SELECTED",
  LOADING: "LOADING",
  //state
  EMAIL_SOC_NETWORKS_SELECTED: "EMAIL_SOC_NETWORKS_SELECTED",
  INITIALS_SELECTED: "INITIALS_SELECTED",
  ADDRESSES_SELECTED: "ADDRESSES_SELECTED",
  LOADING_CATEGORY: "LOADING_CATEGORY",
}
