module.exports = {
  //state
  NOT_INIT: "NOT_INIT",
  NOT_DETERMINE: "NOT_DETERMINE",
  DETERMINED: "DETERMINED",
  CHANGING: "CHANGING",
  //actions
  INIT: "INIT",
  SEND_LOCATION: "SEND_LOCATION",
  SET_DEFAULT: "SET_DEFAULT"
}
