module.exports = {
  //state
  NOT_INIT: "NOT_INIT",
  NOT_DETERMINE: "NOT_DETERMINE",
  DETERMINED: "DETERMINED",
  CHANGING: "CHANGING",
  //actions
  INIT: "INIT",
  SET_COUNTRY: "SET_COUNTRY",
  SET_ADDRESS: "SET_ADDRESS",
  SET_HOUSE: "SET_HOUSE",
  SET_FLAT: "SET_FLAT",
  SEND_LOCATION: "SEND_LOCATION",
  SET_DEFAULT: "SET_DEFAULT"
}
