module.exports = {
  //state
  NOONE: "NOONE",
  SIGNED_IN: "SIGNED_IN",
  ANONYMOUS: "ANONYMOUS",
  AWAITING: "AWAITING",
  //actions
  ATTEMPTING: "ATTEMPTING",
	SIGNIN_USER: "SIGNIN_USER",
	LOGOUT: "LOGOUT"
}
