module.exports = {
// NOTE: states
    PHONE_EXIST: "PHONE_EXIST",
    PHONE_NOT_EXIST:"PHONE_NOT_EXIST",
    WAITING_VERIFICATION_CODE: "WAITING_VERIFICATION_CODE",
// NOTE: actions
    CHANGE_NUMBER: "CHANGE_NUMBER",
    SEND_VERIFICATION_CODE: "SEND_VERIFICATION_CODE",
    VERIFIED: "VERIFIED"
}
