module.exports = {
// NOTE: states
    BIRTHDAY_ON: "BIRTHDAY_ON",
    BIRTHDAY_ON: "BIRTHDAY_ON",
    CART_EXIST: "CART_EXIST",
    GIFT_PRODUCTS_NOT_LOADED: "GIFT_PRODUCTS_NOT_LOADED",
    GIFT_PRODUCTS_LOADED: "GIFT_PRODUCTS_LOADED",
    GIFT_PRODUCTS_LOADING: "GIFT_PRODUCTS_LOADING",
    CART_NOT_INITIALIZED: "CART_NOT_INITIALIZED",
    // NOTE: actions
    CHOOSE_GIFT: "CHOOSE_GIFT",
    REMOVE_GIFT: "REMOVE_GIFT",
    LOADING_GIFT_PRODUCTS: "LOADING_GIFT_PRODUCTS",
    SET_GIFT_PRODUCTS: "SET_GIFT_PRODUCTS",
    UPDATE_CART: "UPDATE_CART",
    SET_GIFT_PRODUCTS: "SET_GIFT_PRODUCTS",
    BIRTHDAY_DICOUNT_ON: "BIRTHDAY_DICOUNT_ON",
    BIRTHDAY_DICOUNT_OFF: "BIRTHDAY_DICOUNT_OFF"
}
