module.exports = {
// NOTE: states
    CART_EXIST: "CART_EXIST",
    CART_NOT_INITIALIZED: "CART_NOT_INITIALIZED",
    // NOTE: actions
    UPDATE_CART: "UPDATE_CART",
    BIRTHDAY_DICOUNT_ON: "BIRTHDAY_DICOUNT_ON",
    BIRTHDAY_DICOUNT_OFF: "BIRTHDAY_DICOUNT_OFF"
}
